### GET FUNCIONARIOS
GET http://localhost:8383/funcionarios

### GET FUNCIONARIO
GET http://localhost:8383/funcionarios/vm9ubobFixwBPJr1DJ2L

### ADD A FUNCIONARIO
POST http://localhost:8383/addfuncionario
Content-Type: application/json

{
    "nome": "Carlos Eduardo",
    "departamento": "Marketing",
    "cidade_trabalho": "Belo Horizonte",
    "cidade_nascimento": "Salvador",
    "sexo": "Masculino",
    "data_nascimento": "1988-03-10",
    "cidade_residência": "Belo Horizonte",
    "data_admissão": "2018-01-15",
    "data_demissão": null
}

# ### UPDATE STATUS OF A FRIEND
# PATCH http://localhost:8383/changestatus
# Content-Type: application/json

# {
#     "nome": "João Silva",
# }


# ###DELETE A FRIEND
# DELETE http://localhost:8383/friends
# Content-Type: application/json

# {
#     "name": "banana"
# }


