### GET FUNCIONARIOS
GET http://localhost:8383/funcionarios

### GET FUNCIONARIO
GET http://localhost:8383/funcionarios/vm9ubobFixwBPJr1DJ2L

### ADD A FUNCIONARIO
POST http://localhost:8383/addfuncionario
Content-Type: application/json

{
    "nome": "Carlos Eduardo",
    "departamento": "Marketing",
    "cidade_trabalho": "Belo Horizonte",
    "cidade_nascimento": "Salvador",
    "sexo": "Masculino",
    "data_nascimento": "1988-03-10",
    "cidade_residência": "Belo Horizonte",
    "data_admissão": "2018-01-15",
    "data_demissão": null
}

### UPDATE departamento OF Func
PATCH http://localhost:8383/changedepartamento/PKAELrb8itikHgDO3BQv
Content-Type: application/json

{
    "atributo": "departamento", "newStatus": "TI"
}


###DELETE campo data_demissão
DELETE http://localhost:8383/removeatributo/vm9ubobFixwBPJr1DJ2L
Content-Type: application/json

{
    "atributo": "data_demissão"
}

###DELETE funcionario
DELETE http://localhost:8383/funcionario/r0MKu8s3HsumBlj1Xwf9
Content-Type: application/json

### ADD DEPENDENTE
POST http://localhost:8383/adddependente
Content-Type: application/json

{
    "nome": "Jorge Matias",
    "data_nascimento": "2012-12-10",
    "cidade_nascimento": "Peruíbe",
    "sexo": "Masculino",
    "grau": "Filho",
    "funcionario_id": "8wXhNpNqpETKhVyONLeh"
}

### GET DEPENDENTES POR FUNCIONARIO
GET http://localhost:8383/funcionario/8wXhNpNqpETKhVyONLeh/dependente

### DELETE DEPENDENTES
DELETE http://localhost:8383/dependente/AAIbzrntUoJZ0jl958mH
